CREATE TABLE IF NOT EXISTS rebate_application_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id VARCHAR(30) NOT NULL,
    vendor_name VARCHAR(100) NOT NULL,
    product_code VARCHAR(20) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(18, 2) NOT NULL,
    rebate_percentage DECIMAL(5, 2) NOT NULL,
    remarks VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE ALIAS IF NOT EXISTS sp_submit_rebate_application FOR
"com.example.rebates.config.H2StoredProcedureFunctions.spSubmitRebateApplication";
